version: '{branch}.{build}'
configuration: RelWithDebInfo
clone_depth: 1
before_build:
- mkdir BLD
- cd BLD
- cmake -G "Visual Studio 14 2015" -DBUILD_BINDING_DOTNET=OFF -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\lib32-msvc-14.0 ../qpid/cpp
- cd ..
build:
  project: BLD\qpid-cpp.sln
  parallel: true
  verbosity: normal
